### ISSUE TITLE
Advanced meta failed

### ISSUE THREAD

**Issue by 89z** [Battleman/zoomdl#74]
**Prerequisite**

- [x] I have updated to the latest version,
- [x] (If applicable) I have ensured the password is correct with the flag `-v 0`,
- [x] I have searched the opened and closed issues for a duplicate,

**Describe the bug**

~~~
PS D:\Desktop> .\zoomdl.exe -p 'w0DP7nn*' `
-u https://us06web.zoom.us/rec/share/5Qb3qHy_bi9WcGazy4W5j80PrQkOpbNIrgW-6vrRkRb5Q2xyxw7RWTJNG2KcO4J4.K-16KTWChtQT-R2h
Advanced meta failed
No video URL in meta, going bruteforce
[ERROR] Video not found in page. Is it login-protected?
Try to refresh the webpage, and export cookies again
Unable to find metadata, aborting.
~~~

**Versions (please complete the following information):**
 - OS: Windows 10
 - Python Version: 3.9.9

**Comment by alexlegresley** [comment]
This is not a valid URL per the documentation. It must contain rec/play instead of rec/share. The URL of the video obtained after inputting the password is needed.

Interestingly, I tried the password option with the correct URL and it produced the same error:
`zoomdl -p "w0DP7nn*" -u "https://us06web.zoom.us/rec/play/Si0es4ltwZ_t9WwjLJ144iPvS0s-E9C41mxYUIKcIgTMgFKPNO9JCpJdW8OhF5W1yBASxPrp0z3BcH6x.2-VzdH-NJbUMmqCT?continueMode=true&_x_zm_rtaid=F79MtpoYR3SAkefhaEw93A.1643258294012.ae96f017920b3eaeb3291356f704b7be&_x_zm_rhtaid=742"
Advanced meta failed
No video URL in meta, going bruteforce
[ERROR] Video not found in page. Is it login-protected? 
Try to refresh the webpage, and export cookies again
Unable to find metadata, aborting.`

However, it downloaded successfully using the cookie option described in the documentation:
`zoomdl -u "https://us06web.zoom.us/rec/play/Si0es4ltwZ_t9WwjLJ144iPvS0s-E9C41mxYUIKcIgTMgFKPNO9JCpJdW8OhF5W1yBASxPrp0z3BcH6x.2-VzdH-NJbUMmqCT?continueMode=true&_x_zm_rtaid=F79MtpoYR3SAkefhaEw93A.1643258294012.ae96f017920b3eaeb3291356f704b7be&_x_zm_rhtaid=742" --cookies cookies.txt`

Based on this issue and personal experience with my university zoom domain, I suspect that videos from university domains require the cookies option, even when explicit sign-in for a particular video is not required.

It's probably worth a note that only the cookie option should be used. Attempting to use both the password and cookie options results in a critical error, as noted in https://github.com/Battleman/zoomdl/issues/48.

**Comment by paulz1** [comment]
I could confirm that in the similar situation it works for as well using cookies option.

But, before the similar urls were downloaded without using cookies just with password.
